### ISSUE TITLE
With front doesn't appear to work

### ISSUE THREAD

**Issue by SedueRey** [Graffino/Custom-Post-Type-Maker#10]
Hello again,

I've trying to make a custom post type without using with_front and it always returns the custom post slug. I've installed 1.1.3 version and I can't figure out what I am doing wrong. 

My custom post is named "escapadas" and with or without front all escapadas has /escapadas/ on their URL.

Best regards,

**Comment by SedueRey** [comment]
![image](https://user-images.githubusercontent.com/3238226/31933904-cc35a2dc-b8aa-11e7-9d99-34fd0e99810c.png)

This is my configuration for escapadas.

**Comment by SedueRey** [comment]
Also, I've tried to add a new one instead editing it and it doesn't work either :(

**Comment by SedueRey** [comment]
I think I found it ... this is not on your plugin, it's related with this https://wordpress.stackexchange.com/questions/28168/taxonomy-why-with-front-false-does-not-work

Maybe this awesome plugin could do that or is it beyond scope?

Feel free to close this if it's beyond scope.

Thanks,

**Comment by zenopopovici** [comment]
@SedueRey I will see what I can do but it will take a while. Workload is huge right now.

**Comment by zenopopovici** [comment]
Not in the scope of this plugin. Sorry. Sorry also for the long wait.
