### ISSUE TITLE
Custom post type to display archives

### ISSUE THREAD

**Issue by germizor** [Graffino/Custom-Post-Type-Maker#12]
Hi there, I've installed your plugin as a secondary option to a blog. I'd like the plugin to display the archives of its posts in a sidebar via widgets. When I enable my sidebar and use the Archives widget, it only shows me the archives from my blog posts and it doesn't pull in the posts from the custom post type. How do I enable this?

**Comment by zenopopovici** [comment]
Not the scope of this plugin:

https://wordpress.stackexchange.com/questions/154696/custom-post-type-posts-dont-show-in-archive-widget
