### ISSUE TITLE
Tabindex

### ISSUE THREAD

**Issue by mmoollllee** [Graffino/Custom-Post-Type-Maker#16]
Hi there!

The Tab-index isn't right for the create new Posttype page. It will jump right to publish and "Add Icon". Can we fix this?

**Comment by zenopopovici** [comment]
It isn't critical and our time is a bit limited. Feel free to submit a PR or give us time to fix it.

**Comment by zenopopovici** [comment]
v1.1.6 is now released and propagating. Thanks!
