### ISSUE TITLE
Make Post Titles Localizable

### ISSUE THREAD

**Issue by jaydeesigns** [Graffino/Custom-Post-Type-Maker#18]
Hello, would it be possible to register "cptm_label" and "cptm_name" as a localizable string so developers can translate them via their theme's .po file? Something like...
Instead of: 
`'cptm_label'               => $cptm_label`

This:
`'cptm_label'               => __($cptm_label, $my_theme->get( 'TextDomain' ))`

Thank you for this great plugin!

**Comment by zenopopovici** [comment]
@jaydeesigns We're a bit overwhelmed right now, but will implement this soon.

**Comment by zenopopovici** [comment]
This is already possible:

```php
// See line 317
__( $cptm_post_type['cptm_label'], 'custom-post-type-maker' )
```
