### ISSUE TITLE
Undefined variable: cptm_singular_name in class-cptm.php

### ISSUE THREAD

**Issue by Eklado** [Graffino/Custom-Post-Type-Maker#21]
After upgrade to version 1.1.7, I got the following message in the Post type singular name:
`<br /><b>Notice</b>:  Undefined variable: cptm_singular_name in <b>/var/www/html/wp-content/plugins/custom-post-type-maker/class-cptm.php</b> on line <b>569</b><br />`

I checked the code and I found that there is a typo in line 480 in class-cptm.php file.
`$cptm_singular_nam`  misses an `e` at the end to be `$cptm_singular_name`.
This should fix the issue.

I am using WordPress 5.2.3 with Custom Post Type Maker Version 1.1.7

**Comment by zenopopovici** [comment]
Fixed. Releasing asap.
