### ISSUE TITLE
conflict with Elementor targeting

### ISSUE THREAD

**Issue by violllettta** [Graffino/Custom-Post-Type-Maker#22]
Hello there, 

Thank you so much for this plugin. I've been using it for years.  In coordination with Advanced Custom Fields and Elementor Pro it enables me to build very complex websites. 

Recently I had a problem and after deactivating my plugins one by one I was able to determine that Custom Post Type Maker is causing this problem: 

• The Elementor Pro Theme Builder allows the designer to create templates and then "target" them at different types of content. 
• With Custom Post Type Maker activated, any existing targeting operates correctly, but when I create a new template and try to select its targets from the dynamic menu, most of the target options do not appear. When I deactivate the CPTM plugin, the targeting menu includes all options. 
• I hoped that the targeting would stick even when the CPTM is reactivated, but I just tested that and discovered that while most of the Elementor targeting does work, targeting for archives and search will not work with CPTM activated. 

I don't know how to get a screenshot with the drop-down menu open, which is why I have not included it. If you know a way to do this, tell me and I will do so. 

Also I can tell you that in trying to research the problem, I compared with another of my websites, which happens not to have wordpress autoupdater, so I was able to discover something that might be helpful: 

The problem described above EXISTS in this configuration: 
WordPress 5.6.2
Elementor version 3.1.3 + Pro v. 3.1.0
CPTM Version 1.1.13

The problem DOES NOT EXIST in this configuration (Elementor targeting works correctly with CPTM activated)
Wordpress 5.4.4
Elementor version Version 3.1.1 + Pro v. Version 3.0.10 
CPTM Version 1.1.13 

Thank you again for all your work and I hope this bug report is helpful. 

Violet

**Comment by zenopopovici** [comment]
@violllettta I've checked and this seems to be an elementor issue, please report this to them. We're only using 	`register_post_type( $cptm_post_type['cptm_name'], $args )` to register the post type. We're not doing anything else.

From the tests you've ran it's obvious that somewhere between elementor `3.1.1` and `3.1.3` something has been introduced in elementor that causes this behaviour.
