### ISSUE TITLE
conflict with elementor 

### ISSUE THREAD

**Issue by violllettta** [Graffino/Custom-Post-Type-Maker#23]
I've been using your plugin for many years and I'm very grateful for it. 

I have elementor pro which enables me to apply templates to custom post types etc. 
It also allows me to create a template that I apply to search results. 

For some strange reason, custom post maker plugin blocks the elementor template from loading on the search results page. 
I've attached a system report and images of the search results page with custom post maker activated and deactivated. 

Thank you for your help,

[system-info-tangoforge.com-16-12-2022.txt](https://github.com/Graffino/Custom-Post-Type-Maker/files/10250028/system-info-tangoforge.com-16-12-2022.txt)
![custom post types maker plugin DEactiveD](https://user-images.githubusercontent.com/6184697/208208945-73836d77-9a91-47b9-94d1-c1b991f0961d.png)
![custom post types maker plugin active](https://user-images.githubusercontent.com/6184697/208208958-34e051fe-1ea0-4588-a77b-a9ebf9956bba.png)

**Comment by zenopopovici** [comment]
Most probably the conflict is with another plugin. This plugin is only using the WordPress custom post type API to create and populate custom post types.
