### ISSUE TITLE
Category Slug

### ISSUE THREAD

**Issue by mikewgd** [Graffino/Custom-Post-Type-Maker#3]
Is it possible to have the category as part of the slug? For example I am using this plugin for adoptable animals. So I created an Our Animals post type. And from there I want categories per animal so cat and dog. Is that possible with this plugin?

/animals/dogs/animal-name

And then I would like /animals to be a page and /animals/dogs list out all the dogs. How can I achieve this? Thanks!

**Comment by zenopopovici** [comment]
Yes with: "custom-post-name/custom-category/custom-category-term". Then you will have to create a category archive page to list all categories.

Custom categories are available via the plugin. They work right out of the box.

I cannot assist you with the implementation however, as it it out of the scope of this plugin, and we're not offering free implementation support.
