### ISSUE TITLE
Menu order seems to be broken or only work for last custom post type created when multiple CPTs have menu position entered

### ISSUE THREAD

**Issue by randycochran** [Graffino/Custom-Post-Type-Maker#4]
I have two custom post types: work, and ideas:

![image](https://cloud.githubusercontent.com/assets/7914311/24255810/d89e2a5e-0fbc-11e7-8f6d-f1212264fd89.png)

Work is set to 'Menu Position' of 2:

![image](https://cloud.githubusercontent.com/assets/7914311/24255862/faf44688-0fbc-11e7-9800-9f3f88133604.png)

Ideas is set to 'Menu Position' of 3:

![image](https://cloud.githubusercontent.com/assets/7914311/24255892/155afed6-0fbd-11e7-8100-f729cdb86244.png)

Yet Ideas appears below 'Dashboard' and Work appears below 'Posts' as shown in the first screen capture.

**Comment by zenopopovici** [comment]
Will investigate. It will take a bit I'm swamped.

**Comment by zenopopovici** [comment]
This is a Wordpress bug, other values look fine. Also the menu_position is updated correctly. Just use other values. Please report it to Wordpress.org.
