### ISSUE TITLE
Enable Comments? 

### ISSUE THREAD

**Issue by AmBacchusRBM** [Graffino/Custom-Post-Type-Maker#6]
Hi, I am trying to add support for comments and am having trouble getting them to work with this plugin. 

I've tried:
add_post_type_support( 'my_custom_post_type', array( 'comments' ) );

And have tried adding a filter to wp_inster_post_data that sets the comment status to 1, but neither seem to be working. Any ideas would be greatly appreciated?

**Comment by zenopopovici** [comment]
Go to the post scroll down and enable comments.
