### ISSUE TITLE
Types created by Custom Post Type Maker show up under "Other registered Custom Post Types"

### ISSUE THREAD

**Issue by gotmikhail** [Graffino/Custom-Post-Type-Maker#8]
Have a pretty "raw" installation of WordPress to try out a way to make custom posts.

WordPress 4.8.1
CPTM 1.1.3

Create type, go w/ defaults, type shows up under "Other registered Custom Post Type"

![custom_post_type](https://user-images.githubusercontent.com/356867/29634654-87b27e86-8818-11e7-9d30-fd950c0d97e6.PNG)

**Comment by zenopopovici** [comment]
Keep in mind that post-type-names must be all LOWERCASE. It's explicitly specified in the "Add  New Custom Post".
You basically created 4 post types that have the same name but  case differs.

**Comment by gotmikhail** [comment]
apologies 👍
