### ISSUE TITLE
API Rest endpoint for custom post type

### ISSUE THREAD

**Issue by SedueRey** [Graffino/Custom-Post-Type-Maker#9]
Hello,

I'm using your great plugin in a couple websites and now I can't figure out if there's an option to make my custom post types available on the wordpress Rest API Json.

Am I making anything wrong?

Thanks

**Comment by zenopopovici** [comment]
@SedueRey It should work out of the box, as I'm using the WP PHP API. I will check. It's going to take a coulple of weeks, I'm on holidays.

**Comment by zenopopovici** [comment]
@SedueRey Has this been solved, or?

**Comment by SedueRey** [comment]
Yes, this was a problem with another plugin not yours.

Thanks for all
